Repository Heesu01/myongji_roomMate, pull requests merged in 2024-08, with the labels that each got.

#26 setting: axios
  src/api/Axios.js
  src/api/ChatApi.js
  src/api/DormitoryApi.js
  src/api/LoginApi.js
  src/api/MainApi.js
  src/api/MyApi.js
  src/api/RoomApi.js
  src/api/WriteApi.js
Labels: 🔗 api, ⚙️ setting

#27 feature/responsiveHeader
  src/components/Header.js
Labels: 🖥️ responsive

#30 feature/responsiveMyPage
  src/components/MyList.js
  src/pages/MyPage.js
Labels: 🖥️ responsive

#32 Feature/dormitoryApi
  src/api/DormitoryApi.js
  src/components/Header.js
  src/pages/DormitoryPage.js
  src/pages/MainPage.js
Labels: 🔗 api

#34 feature/CoutChoseBlx
  src/App.js
  src/pages/DormitoryPage.js
Labels: ⚒️ fix, 🌱 feature

#35 Feature/roomApi
  src/App.js
  src/api/RoomApi.js
  src/components/List.js
  src/pages/DormitoryPage.js
  src/pages/RoomPage.js
Labels: 🔗 api

#36 feature/logoutApi
  src/api/LoginApi.js
  src/components/Header.js
  src/components/Map.js
  src/pages/MainPage.js
Labels: 🔗 api

#37 feature/WriteApi
  src/api/WriteApi.js
  src/components/CountChoseBox.js
  src/components/List.js
  src/pages/DormitoryPage.js
  src/pages/WritePage.js
Labels: 🔗 api

#38 Feature/mypageApi
  src/api/MyApi.js
  src/pages/MyPage.js
Labels: 🔗 api

#39 Feature/edit api
  src/api/RoomApi.js
  src/pages/RoomPage.js
  src/pages/WritePage.js
Labels: 🔗 api

#42 Feature/fixDesign#4
  src/components/Footer.js
  src/components/Header.js
  src/pages/InfoPage.js
  src/pages/MainPage.js
Labels: ⚒️ fix, 🖥️ responsive, 🌱 feature

#43 Feature/infoApi
  src/api/MyApi.js
  src/components/Info.js
  src/components/MyList.js
  src/pages/MyPage.js
Labels: 🔗 api, 🖥️ responsive

#44 Feature/fixDesign#5
  src/pages/InfoPage.js
  src/pages/Login.js
  src/pages/MyPage.js
  src/styles/Theme.js
Labels: ⚒️ fix, 🖥️ responsive

#47 Feature/fix design#6
  src/api/LoginApi.js
  src/api/MyApi.js
  src/components/Header.js
  src/components/List.js
  src/components/MyList.js
  src/pages/MainPage.js
  src/pages/MyPage.js
Labels: 🔗 api, ⚒️ fix

#50 Feature/design#7-loading
  src/pages/DormitoryPage.js
  src/pages/MyPage.js
  src/pages/RoomPage.js
Labels: 🎨 UI

#51 Feature/alertModal
  src/api/LoginApi.js
  src/components/Header.js
  src/components/Modal.js
  src/pages/Login.js
  src/pages/MainPage.js
  src/pages/RoomPage.js
Labels: ⚒️ fix, 🌱 feature

#52 Feature/fixGenderApi
  src/components/List.js
  src/pages/DormitoryPage.js
Labels: 🔗 api, ⚒️ fix

#53 Feature/chatApi
  package.json
  src/components/ChatRoomList.js
  src/pages/ChatPage.js
  yarn.lock
Labels: 🔗 api

#55 Feature/like
  src/components/List.js
  src/images/emptyStar.svg
  src/images/fullStar.svg
Labels: 🎨 UI

#56 Feature/like
  src/components/List.js
  src/pages/RoomPage.js
Labels: ⚒️ fix, 🎨 UI

#57 Feature/fixDesign#8
  src/components/Info.js
Labels: ⚒️ fix

#58 Feature/like api
  src/api/RoomApi.js
  src/components/List.js
  src/pages/DormitoryPage.js
  src/pages/RoomPage.js
Labels: 🔗 api

#60 Feature/my page api
  src/api/MyApi.js
  src/components/MyList.js
  src/pages/MyPage.js
Labels: 🔗 api, 🎨 UI

#59 Feature/SocketApi#2
  src/components/ChatRoomList.js
  src/pages/ChatPage.js
  src/pages/RoomPage.js
Labels: 🔗 api, ⚒️ fix

#61 Feature/fix design#9
  src/api/LoginApi.js
  src/api/MyApi.js
  src/components/List.js
  src/pages/DormitoryPage.js
  src/pages/MainPage.js
  src/pages/MyPage.js
Labels: ⚒️ fix

#62 Feature/fix design#9
  src/api/DormitoryApi.js
  src/components/Category.js
  src/components/Header.js
  src/components/Info.js
  src/components/List.js
  src/pages/MyPage.js
  src/styles/GlobalStyle.js
Labels: ⚒️ fix

#63 Feature/fixDesign#10
  src/components/ChatRoomList.js
  src/pages/ChatPage.js
  src/pages/MainPage.js
Labels: ⚒️ fix

#65 Feature/fix design#11
  src/api/CategoryApi.js
  src/api/DormitoryApi.js
  src/api/MyApi.js
  src/components/CountChoseBox.js
  src/components/Footer.js
  src/components/Header.js
  src/components/Info.js
  src/components/List.js
  src/components/Modal.js
  src/components/NameGender.js
  src/pages/DormitoryPage.js
  src/pages/Login.js
  src/pages/MyPage.js
  src/pages/RoomPage.js
  src/pages/WritePage.js
Labels: ⚒️ fix, 🎨 UI

#64 Feature/SocketApi#3
  src/components/ChatRoomList.js
  src/components/Layout.js
  src/pages/ChatPage.js
Labels: ⚒️ fix, 🖥️ responsive

#66 Feature/otherInfoApi
  src/components/OtherInfo.js
  src/images/tag.png
  src/pages/ChatPage.js
Labels: 🔗 api, 🌱 feature

#67 Hotfix
  src/components/OtherInfo.js
Labels: hotfix
